version: "3.7"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
       - ./api:/usr/src/app
    env_file: .env
  ui:
    build: ./ui
    ports:
      - "3001:3001"
    volumes:
       - ./ui:/usr/src/app
    env_file: .env
    environment:
      PORT: 3001
